In [110]:
import pandas as pd
import numpy as np

movie_rating_df = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/movie_rating_df.csv')

In [111]:
director_writers = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/directors_writers.csv')
name_df = pd.read_csv('https://storage.googleapis.com/dqlab-dataset/actor_name.csv')

In [112]:
movie_rating_df.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes
0,tt0000001,short,Carmencita,Carmencita,0,1894.0,NaN,1.0,"Documentary,Short",5.6,1608
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892.0,NaN,5.0,"Animation,Short",6.0,197
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892.0,NaN,4.0,"Animation,Comedy,Romance",6.5,1285
3,tt0000004,short,Un bon bock,Un bon bock,0,1892.0,NaN,12.0,"Animation,Short",6.1,121
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893.0,NaN,1.0,"Comedy,Short",6.1,2050

In [113]:
director_writers.head()

,tconst,director_name,writer_name
0,tt0011414,David Kirkland,"John Emerson,Anita Loos"
1,tt0011890,Roy William Neill,"Arthur F. Goodrich,Burns Mantle,Mary Murillo"
2,tt0014341,"Buster Keaton,John G. Blystone","Jean C. Havez,Clyde Bruckman,Joseph A. Mitchell"
3,tt0018054,Cecil B. DeMille,Jeanie Macpherson
4,tt0024151,James Cruze,"Max Miller,Wells Root,Jack Jevne"

In [114]:
name_df.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm1774132,Nathan McLaughlin,1973,\N,"special_effects,make_up_department","tt0417686,tt1713976,tt1891860,tt0454839"
1,nm10683464,Bridge Andrew,\N,\N,actor,tt7718088
2,nm1021485,Brandon Fransvaag,\N,\N,miscellaneous,tt0168790
3,nm6940929,Erwin van der Lely,\N,\N,miscellaneous,tt4232168
4,nm5764974,Svetlana Shypitsyna,\N,\N,actress,tt3014168

In [115]:
print("info dataset movie rating: ",movie_rating_df.info())
print("info dataset director writers: ",director_writers.info())
print("info dataset actor film: ",name_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 751614 entries, 0 to 751613
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   tconst          751614 non-null  object
 1   titleType       751614 non-null  object
 2   primaryTitle    751614 non-null  object
 3   originalTitle   751614 non-null  object
 4   isAdult         751614 non-null  int64
 5   startYear       751614 non-null  float64
 6   endYear         16072 non-null   float64
 7   runtimeMinutes  751614 non-null  float64
 8   genres          486766 non-null  object
 9   averageRating   751614 non-null  float64
 10  numVotes        751614 non-null  int64
dtypes: float64(4), int64(2), object(5)
memory usage: 63.1+ MB
info dataset movie rating:  None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986 entries, 0 to 985
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tconst         986 non-null    object
 1   director_name  986 non-null    object
 2   writer_name    986 non-null    object
dtypes: object(3)
memory usage: 23.2+ KB
info dataset director writers:  None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nconst             1000 non-null   object
 1   primaryName        1000 non-null   object
 2   birthYear          1000 non-null   object
 3   deathYear          1000 non-null   object
 4   primaryProfession  891 non-null    object
 5   knownForTitles     1000 non-null   object
dtypes: object(6)
memory usage: 47.0+ KB
info dataset actor film:  None

In [116]:
print(movie_rating_df.shape)
print(director_writers.shape)
print(name_df.shape)

(751614, 11)
(986, 3)
(1000, 6)

In [117]:
# Mengubah kolom director_name dan writer_name dari string menjadi list
director_writers['director_name'] = director_writers['director_name'].apply(lambda x: x.split(','))
director_writers['writer_name'] = director_writers['writer_name'].apply(lambda x: x.split(','))

# Menampilkan 5 baris teratas
print(director_writers.head())

      tconst                      director_name  \
0  tt0011414                   [David Kirkland]
1  tt0011890                [Roy William Neill]
2  tt0014341  [Buster Keaton, John G. Blystone]
3  tt0018054                 [Cecil B. DeMille]
4  tt0024151                      [James Cruze]

                                         writer_name
0                         [John Emerson, Anita Loos]
1   [Arthur F. Goodrich, Burns Mantle, Mary Murillo]
2  [Jean C. Havez, Clyde Bruckman, Joseph A. Mitc...
3                                [Jeanie Macpherson]
4               [Max Miller, Wells Root, Jack Jevne]

In [118]:
#Kita hanya akan membutuhkan kolom nconst, primaryName, dan knownForTitles
name_df = name_df[['nconst', 'primaryName', 'knownForTitles']]

#Tampilkan 5 baris teratas dari name_df
name_df.head()

       nconst          primaryName                           knownForTitles
0   nm1774132    Nathan McLaughlin  tt0417686,tt1713976,tt1891860,tt0454839
1  nm10683464        Bridge Andrew                                tt7718088
2   nm1021485    Brandon Fransvaag                                tt0168790
3   nm6940929   Erwin van der Lely                                tt4232168
4   nm5764974  Svetlana Shypitsyna                                tt3014168

In [119]:
#Melakukan pengecekan variasi
print(name_df['knownForTitles'].apply(lambda x: len(x.split(','))).unique())

#Mengubah knownForTitles menjadi list of list
name_df['knownForTitles'] = name_df['knownForTitles'].apply(lambda x: x.split(','))

#Mencetak 5 baris teratas
name_df.head()

[4 1 2 3]

<ipython-input-119-ca82e4b18c3e>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name_df['knownForTitles'] = name_df['knownForTitles'].apply(lambda x: x.split(','))

,nconst,primaryName,knownForTitles
0,nm1774132,Nathan McLaughlin,"[tt0417686, tt1713976, tt1891860, tt0454839]"
1,nm10683464,Bridge Andrew,[tt7718088]
2,nm1021485,Brandon Fransvaag,[tt0168790]
3,nm6940929,Erwin van der Lely,[tt4232168]
4,nm5764974,Svetlana Shypitsyna,[tt3014168]

In [120]:
# Menyiapkan bucket untuk dataframe hasil unnest
df_uni = []

# Melakukan unnesting kolom 'knownForTitles'
for x in ['knownForTitles']:
    # Mengulang indeks sesuai panjang list di setiap baris
    idx = name_df.index.repeat(name_df[x].str.len())

    # Membuat dataframe baru dari elemen-elemen list yang sudah dipecah
    df1 = pd.DataFrame({
        x: np.concatenate(name_df[x].values)
    })

    # Mengatur indeks df1 agar cocok dengan indeks yang diulang
    df1.index = idx

    # Menambahkan dataframe ke dalam bucket
    df_uni.append(df1)

# Menggabungkan semua dataframe menjadi satu
df_concat = pd.concat(df_uni, axis=1)

# Left join dengan dataframe awal tanpa kolom 'knownForTitles'
unnested_df = df_concat.join(name_df.drop(['knownForTitles'], axis=1), how='left')

# Mengatur urutan kolom agar sesuai dengan dataframe awal
unnested_df = unnested_df[name_df.columns.tolist()]

# Menampilkan hasil akhir
unnested_df.head()

       nconst        primaryName knownForTitles
0   nm1774132  Nathan McLaughlin      tt0417686
0   nm1774132  Nathan McLaughlin      tt1713976
0   nm1774132  Nathan McLaughlin      tt1891860
0   nm1774132  Nathan McLaughlin      tt0454839
1  nm10683464      Bridge Andrew      tt7718088

In [121]:
#menyiapkan bucket untuk dataframe
df_uni = []

for col in ['primaryName']:
    #agregasi kolom PrimaryName sesuai group_col yang sudah di define di atas
    dfi = unnested_df.groupby(['knownForTitles'])[col].apply(list)
    #Lakukan append
    df_uni.append(dfi)
df_grouped = pd.concat(df_uni, axis=1).reset_index()
df_grouped.columns = ['knownForTitles','cast_name']
df_grouped.head(10)

  knownForTitles           cast_name
0      tt0008125    [Charles Harley]
1      tt0009706    [Charles Harley]
2      tt0010304  [Natalie Talmadge]
3      tt0011414  [Natalie Talmadge]
4      tt0011890  [Natalie Talmadge]
5      tt0014341  [Natalie Talmadge]
6      tt0016622     [Booth Grainge]
7      tt0018054     [Reeka Roberts]
8      tt0024151     [James Hackett]
9      tt0025981    [Bernard Loftus]

In [123]:
#join antara movie table dan cast table
base_df = pd.merge(df_grouped, movie_rating_df, left_on='knownForTitles', right_on='tconst', how='inner')

#join antara base_df dengan director_writer table
base_df = pd.merge(base_df, director_writers, left_on='tconst', right_on='tconst', how='left')
base_df.head()

,knownForTitles,cast_name,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,director_name,writer_name
0,tt0011414,[Natalie Talmadge],tt0011414,movie,The Love Expert,The Love Expert,0,1920.0,NaN,60.0,"Comedy,Romance",4.9,136,[David Kirkland],"[John Emerson, Anita Loos]"
1,tt0011890,[Natalie Talmadge],tt0011890,movie,Yes or No,Yes or No,0,1920.0,NaN,72.0,NaN,6.3,7,[Roy William Neill],"[Arthur F. Goodrich, Burns Mantle, Mary Murillo]"
2,tt0014341,[Natalie Talmadge],tt0014341,movie,Our Hospitality,Our Hospitality,0,1923.0,NaN,65.0,"Comedy,Romance,Thriller",7.8,9621,"[Buster Keaton, John G. Blystone]","[Jean C. Havez, Clyde Bruckman, Joseph A. Mitc..."
3,tt0018054,[Reeka Roberts],tt0018054,movie,The King of Kings,The King of Kings,0,1927.0,NaN,155.0,"Biography,Drama,History",7.3,1826,[Cecil B. DeMille],[Jeanie Macpherson]
4,tt0024151,[James Hackett],tt0024151,movie,I Cover the Waterfront,I Cover the Waterfront,0,1933.0,NaN,80.0,"Drama,Romance",6.3,455,[James Cruze],"[Max Miller, Wells Root, Jack Jevne]"

#Cleaning Data

In [124]:
base_drop = base_df.drop(['knownForTitles'], axis=1)
print(base_drop.info())
base_drop['genres'] = base_drop['genres'].fillna('Unknown')
print(base_drop.isnull().sum())
base_drop[['director_name','writer_name']] = base_drop[['director_name','writer_name']].fillna('unknown')
base_drop['genres'] = base_drop['genres'].apply(lambda x: x.split(','))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1060 entries, 0 to 1059
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cast_name       1060 non-null   object
 1   tconst          1060 non-null   object
 2   titleType       1060 non-null   object
 3   primaryTitle    1060 non-null   object
 4   originalTitle   1060 non-null   object
 5   isAdult         1060 non-null   int64
 6   startYear       1060 non-null   float64
 7   endYear         110 non-null    float64
 8   runtimeMinutes  1060 non-null   float64
 9   genres          745 non-null    object
 10  averageRating   1060 non-null   float64
 11  numVotes        1060 non-null   int64
 12  director_name   986 non-null    object
 13  writer_name     986 non-null    object
dtypes: float64(4), int64(2), object(8)
memory usage: 116.1+ KB
None
cast_name           0
tconst              0
titleType           0
primaryTitle        0
originalTitle       0
isAdult             0
startYear           0
endYear           950
runtimeMinutes      0
genres              0
averageRating       0
numVotes            0
director_name      74
writer_name        74
dtype: int64

In [126]:
base_drop2 = base_drop.drop(['tconst','isAdult','endYear','originalTitle'], axis=1)
base_drop2 = base_drop2[['primaryTitle','titleType','startYear','runtimeMinutes','genres','averageRating','numVotes','cast_name','director_name','writer_name']]
base_drop2.columns = ['title','type','start','duration','genres','rating','votes','cast_name','director_name','writer_name']
base_drop2.head()

,title,type,start,duration,genres,rating,votes,cast_name,director_name,writer_name
0,The Love Expert,movie,1920.0,60.0,"[Comedy, Romance]",4.9,136,[Natalie Talmadge],[David Kirkland],"[John Emerson, Anita Loos]"
1,Yes or No,movie,1920.0,72.0,[Unknown],6.3,7,[Natalie Talmadge],[Roy William Neill],"[Arthur F. Goodrich, Burns Mantle, Mary Murillo]"
2,Our Hospitality,movie,1923.0,65.0,"[Comedy, Romance, Thriller]",7.8,9621,[Natalie Talmadge],"[Buster Keaton, John G. Blystone]","[Jean C. Havez, Clyde Bruckman, Joseph A. Mitc..."
3,The King of Kings,movie,1927.0,155.0,"[Biography, Drama, History]",7.3,1826,[Reeka Roberts],[Cecil B. DeMille],[Jeanie Macpherson]
4,I Cover the Waterfront,movie,1933.0,80.0,"[Drama, Romance]",6.3,455,[James Hackett],[James Cruze],"[Max Miller, Wells Root, Jack Jevne]"

In [128]:
feature_df = base_drop2[['title','cast_name','genres','director_name','writer_name']]
feature_df.head()

,title,cast_name,genres,director_name,writer_name
0,The Love Expert,[Natalie Talmadge],"[Comedy, Romance]",[David Kirkland],"[John Emerson, Anita Loos]"
1,Yes or No,[Natalie Talmadge],[Unknown],[Roy William Neill],"[Arthur F. Goodrich, Burns Mantle, Mary Murillo]"
2,Our Hospitality,[Natalie Talmadge],"[Comedy, Romance, Thriller]","[Buster Keaton, John G. Blystone]","[Jean C. Havez, Clyde Bruckman, Joseph A. Mitc..."
3,The King of Kings,[Reeka Roberts],"[Biography, Drama, History]",[Cecil B. DeMille],[Jeanie Macpherson]
4,I Cover the Waterfront,[James Hackett],"[Drama, Romance]",[James Cruze],"[Max Miller, Wells Root, Jack Jevne]"

In [130]:
def sanitize(x):
    try:
        if isinstance(x, list):
            return [i.replace(' ','').lower() for i in x]
        else:
            return [x.replace(' ','').lower()]
    except:
        print(x)
feature_cols = ['cast_name','genres','writer_name','director_name']

for col in feature_cols:
    feature_df[col] = feature_df[col].apply(sanitize)

def soup_feature(x):
    return ' '.join(x['cast_name']) + ' ' + ' '.join(x['genres']) + ' ' + ' '.join(x['director_name']) + ' ' + ' '.join(x['writer_name'])

#membuat soup menjadi 1 kolom sendiri
feature_df['soup'] = feature_df.apply(soup_feature, axis=1)

<ipython-input-130-5625751345a9>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature_df[col] = feature_df[col].apply(sanitize)
<ipython-input-130-5625751345a9>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  feature_df['soup'] = feature_df.apply(soup_feature, axis=1)

In [131]:
from sklearn.feature_extraction.text import CountVectorizer

#definisikan CountVectorizer dan mengubah soup tadi menjadi bentuk vector
count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(feature_df['soup'])

print(count)
print(count_matrix.shape)

CountVectorizer(stop_words='english')
(1060, 10026)

In [132]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.15430335 0.35355339 ... 0.         0.         0.13608276]
 [0.15430335 1.         0.10910895 ... 0.         0.         0.        ]
 [0.35355339 0.10910895 1.         ... 0.         0.08703883 0.09622504]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.08703883 ... 0.         1.         0.10050378]
 [0.13608276 0.         0.09622504 ... 0.         0.10050378 1.        ]]

In [133]:
indices = pd.Series(feature_df.index, index=feature_df['title']).drop_duplicates()

def content_recommender(title):
    #mendapatkan index dari judul film yang disebutkan
    idx = indices[title]

    #menjadikan list dari array similarity cosine sim tadi
    #hint: cosine_sim[idx]
    sim_scores = list(enumerate(cosine_sim[idx]))

    #mengurutkan film dari similarity tertinggi ke terendah
    #hint: sorted(iter, key, reverse)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    #untuk mendapatkan list judul dari item kedua sampe ke 11 (abaikan yang pertama karena yang pertama pasti judul film itu sendiri)
    sim_scores = sim_scores[1:11]

    #mendapatkan index dari judul-judul yang muncul di sim_scores
    movie_indices = [i[0] for i in sim_scores]

    #dengan menggunakan iloc, kita bisa panggil balik berdasarkan index dari movie_indices
    return base_df.iloc[movie_indices]

print(content_recommender('The Lion King'))

     knownForTitles                   cast_name      tconst titleType  \
848       tt3040964  [Cristina Carrión Márquez]   tt3040964     movie
383       tt0286336          [Francisco Bretas]   tt0286336  tvSeries
1002      tt7222086          [Hiroki Matsukawa]   tt7222086  tvSeries
73        tt0075147             [Joaquín Parra]   tt0075147     movie
232       tt0119051            [Chris Kosloski]   tt0119051     movie
556      tt10068158          [Hiroki Matsukawa]  tt10068158     movie
9         tt0028657            [Bernard Loftus]   tt0028657     movie
191       tt0107875               [Simon Mayal]   tt0107875     movie
803       tt2356464               [Sina Müller]   tt2356464     movie
983       tt6270328                   [Jo Boag]   tt6270328  tvSeries

                                         primaryTitle  \
848                                   The Jungle Book
383                      The Animals of Farthing Wood
1002                                    Made in Abyss
73                                   Robin and Marian
232                                          The Edge
556                     Made in Abyss: Journey's Dawn
9                               Boss of Lonely Valley
191                       The Princess and the Goblin
803                                           Ostwind
983   The Skinner Boys: Guardians of the Lost Secrets

                                        originalTitle  isAdult  startYear  \
848                                   The Jungle Book        0     2016.0
383                      The Animals of Farthing Wood        0     1993.0
1002                                    Made in Abyss        0     2017.0
73                                   Robin and Marian        0     1976.0
232                                          The Edge        0     1997.0
556                 Made in Abyss: Tabidachi no Yoake        0     2019.0
9                               Boss of Lonely Valley        0     1937.0
191                       The Princess and the Goblin        0     1991.0
803                                           Ostwind        0     2013.0
983   The Skinner Boys: Guardians of the Lost Secrets        0     2014.0

      endYear  runtimeMinutes                       genres  averageRating  \
848       NaN           106.0       Adventure,Drama,Family            7.4
383    1995.0            25.0    Adventure,Animation,Drama            8.3
1002      NaN           325.0    Adventure,Animation,Drama            8.4
73        NaN           106.0      Adventure,Drama,Romance            6.5
232       NaN           117.0       Action,Adventure,Drama            6.9
556       NaN           139.0  Adventure,Animation,Fantasy            7.4
9         NaN            60.0       Action,Adventure,Drama            6.2
191       NaN            82.0   Adventure,Animation,Comedy            6.8
803       NaN           101.0       Adventure,Drama,Family            6.8
983       NaN            23.0    Adventure,Animation,Drama            7.8

      numVotes                                      director_name  \
848     250994                                      [Jon Favreau]
383       3057             [Elphin Lloyd-Jones, Philippe Leclerc]
1002      4577  [Masayuki Kojima, Hitoshi Haga, Shinya Iino, T...
73       10830                                   [Richard Lester]
232      65673                                     [Lee Tamahori]
556         81                                  [Masayuki Kojima]
9           41                                       [Ray Taylor]
191       2350                                     [József Gémes]
803       1350                                [Katja von Garnier]
983         12        [Pablo De La Torre, Eugene Linkov, Jo Boag]

                                            writer_name
848                     [Justin Marks, Rudyard Kipling]
383   [Valerie Georgeson, Colin Dann, Jenny McDade, ...
1002  [Akihito Tsukushi, Keigo Koyanagi, Hideyuki Ku...
73                                      [James Goldman]
232                                       [David Mamet]
556                                  [Akihito Tsukushi]
9                       [Frances Guihan, Forrest Brown]
191                     [Robin Lyons, George MacDonald]
803          [Kristina Magdalena Henn, Lea Schmidbauer]
983   [David Witt, John Derevlany, David Evans, Pete...